<?php

namespace Paprec\CommercialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRequestRepository extends EntityRepository
{
}
