<?php
declare(strict_types=1);

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function isMailUnique($params)
    {
        return $this->findBy([
            'email' => $params['email'],
            'deleted' => null
        ]);
    }

    public function isUsernameUnique($params)
    {
        return $this->findBy([
            'username' => $params['username'],
            'deleted' => null
        ]);
    }

    public function isUsernameCanonicalUnique($params)
    {
        return $this->findBy([
            'usernameCanonical' => $params['username_canonical'],
            'deleted' => null
        ]);
    }
}
