<?php

namespace Paprec\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function isMailUnique($params)
    {
        return $this->findBy(array(
            'email' => $params['email'],
            'deleted' => null
        ));
    }

    public function isUsernameUnique($params)
    {
        return $this->findBy(array(
            'username' => $params['username'],
            'deleted' => null
        ));
    }

    public function isUsernameCanonicalUnique($params)
    {
        return $this->findBy(array(
            'usernameCanonical' => $params['usernameCanonical'],
            'deleted' => null
        ));
    }
}
