### Back Office

fos_user_security_login:
  path:  /admin/login
  controller: App\Controller\SecurityController::loginAction

fos_user_security_check:
  path:  /admin/check
  controller: App\Controller\SecurityController::checkAction

fos_user_security_logout:
  path:  /admin/logout
  controller: App\Controller\SecurityController::logoutAction

### Load files that contains Controllers

paprec_catalog:
  resource: 'routes/catalog.yaml'
  prefix: '/admin/catalog'

paprec_commercial:
  resource: 'routes/commercial.yaml'
  prefix: '/admin/commercial'

paprec_home:
  resource: 'routes/home.yaml'
  prefix: '/admin'

paprec_public:
  resource: 'routes/public.yaml'
  prefix:

paprec_user:
  resource: 'routes/user.yaml'
  prefix: '/admin/user'