# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    paprec_types_picture: ['PICTO', 'PICTURE', 'PILOTPICTURE']
    paprec_custom_area_types_picture: ['LEFT', 'RIGHT']
    paprec_languages: ['DE', 'FR', 'IT', 'EN']
    paprec_custom_area_codes: ['catalog_top']
    paprec_quote_status: ['CREATED', 'PENDING', 'PROCESSING', 'CLOSED']
    paprec_quote_access: ['stairs', 'elevator', 'ground']
    paprec_quote_access_price:
        stairs: 20
        elevator: 10
        ground: 0
    paprec_quote_staff: ['19', '1019', '2029', '3039', '4049', '5059', '6069', '7079', '8089', '9099', '100109', '110119', '120129', '130139', '140149', '150+']

    ### rework ###

    app.data_tmp_directory: '%kernel.project_dir%/data/tmp'
    app.product.picto_path: '%kernel.project_dir%/public/uploads/pictos'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $tmpFolder: '%app.data_tmp_directory%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    ## Declaration des services en plus de l'autowiring

    paprec_commercial.postal_code_transformer:
        class: App\Form\DataTransformer\PostalCodeToStringTransformer
        arguments:
            ['@doctrine.orm.entity_manager']

    paprec_commercial.quote_request_public_form:
        class: App\Form\QuoteRequestPublicType
        tags: ['form.type']
        public: true
        arguments:
            ['@paprec_commercial.postal_code_transformer']

    paprec_commercial.quote_request_form:
        class: App\Form\QuoteRequestType
        tags: ['form.type']
        public: true
        arguments:
            ['@paprec_commercial.postal_code_transformer']

    ### Twig Extension (enable intl for DateTime) ###
    twig.extension.intl:
        class: Twig\Extensions\IntlExtension
        tags:
            - { name: twig.extension }