<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200304114300 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE carts CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE disabled disabled DATETIME DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE frequency frequency VARCHAR(255) DEFAULT NULL, CHANGE frequency_times frequency_times VARCHAR(255) DEFAULT NULL, CHANGE frequency_interval frequency_interval VARCHAR(255) DEFAULT NULL, CHANGE content content JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE users CHANGE salt salt VARCHAR(255) DEFAULT NULL, CHANGE last_login last_login VARCHAR(255) DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE roles roles JSON NOT NULL, CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE deleted deleted DATETIME DEFAULT NULL, CHANGE company_name company_name VARCHAR(255) DEFAULT NULL, CHANGE last_name last_name VARCHAR(255) DEFAULT NULL, CHANGE first_name first_name VARCHAR(255) DEFAULT NULL, CHANGE lang lang VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE quoteRequestLines CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE deleted deleted DATETIME DEFAULT NULL, CHANGE set_up_price set_up_price INT DEFAULT NULL, CHANGE rental_unit_price rental_unit_price INT DEFAULT NULL, CHANGE transport_unit_price transport_unit_price INT DEFAULT NULL, CHANGE treatment_unit_price treatment_unit_price INT DEFAULT NULL, CHANGE traceability_unit_price traceability_unit_price INT DEFAULT NULL, CHANGE transport_rate transport_rate BIGINT DEFAULT NULL, CHANGE treatment_rate treatment_rate BIGINT DEFAULT NULL, CHANGE traceability_rate traceability_rate BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE region CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE deleted deleted DATETIME DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE postalCodes CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE user_in_charge_id user_in_charge_id INT DEFAULT NULL, CHANGE region_id region_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE deleted deleted DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE currencyRates CHANGE rate rate NUMERIC(20, 10) DEFAULT NULL');
        $this->addSql('ALTER TABLE custom_area CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE deleted deleted DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE quoteRequests CHANGE user_creation_id user_creation_id INT DEFAULT NULL, CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE user_in_charge_id user_in_charge_id INT DEFAULT NULL, CHANGE postal_code_id postal_code_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE deleted deleted DATETIME DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE canton canton VARCHAR(255) DEFAULT NULL, CHANGE business_name business_name VARCHAR(255) DEFAULT NULL, CHANGE civility civility VARCHAR(10) DEFAULT NULL, CHANGE last_name last_name VARCHAR(255) DEFAULT NULL, CHANGE first_name first_name VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE total_amount total_amount INT DEFAULT NULL, CHANGE annual_budget annual_budget INT DEFAULT NULL, CHANGE frequency frequency VARCHAR(255) DEFAULT NULL, CHANGE frequency_times frequency_times VARCHAR(255) DEFAULT NULL, CHANGE frequency_interval frequency_interval VARCHAR(255) DEFAULT NULL, CHANGE customer_id customer_id VARCHAR(255) DEFAULT NULL, CHANGE reference reference VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE productLabels CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE product_id product_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE deleted deleted DATETIME DEFAULT NULL, CHANGE product_version product_version VARCHAR(255) DEFAULT NULL, CHANGE lock_type lock_type VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE products CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT NULL, CHANGE deleted deleted DATETIME DEFAULT NULL, CHANGE rental_unit_price rental_unit_price INT DEFAULT NULL, CHANGE transport_unit_price transport_unit_price INT DEFAULT NULL, CHANGE treatment_unit_price treatment_unit_price INT DEFAULT NULL, CHANGE traceability_unit_price traceability_unit_price INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pictures CHANGE product_id product_id INT DEFAULT NULL, CHANGE custom_area_id custom_area_id INT DEFAULT NULL, CHANGE path path VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE carts CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE disabled disabled DATETIME DEFAULT \'NULL\', CHANGE city city VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE frequency frequency VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE frequency_times frequency_times VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE frequency_interval frequency_interval VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE content content LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE currencyRates CHANGE rate rate NUMERIC(20, 10) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE custom_area CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE deleted deleted DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE pictures CHANGE product_id product_id INT DEFAULT NULL, CHANGE custom_area_id custom_area_id INT DEFAULT NULL, CHANGE path path VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE postalCodes CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE user_in_charge_id user_in_charge_id INT DEFAULT NULL, CHANGE region_id region_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE deleted deleted DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE productLabels CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE product_id product_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE deleted deleted DATETIME DEFAULT \'NULL\', CHANGE product_version product_version VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE lock_type lock_type VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE products CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE deleted deleted DATETIME DEFAULT \'NULL\', CHANGE rental_unit_price rental_unit_price INT DEFAULT NULL, CHANGE transport_unit_price transport_unit_price INT DEFAULT NULL, CHANGE treatment_unit_price treatment_unit_price INT DEFAULT NULL, CHANGE traceability_unit_price traceability_unit_price INT DEFAULT NULL');
        $this->addSql('ALTER TABLE quoteRequestLines CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE deleted deleted DATETIME DEFAULT \'NULL\', CHANGE set_up_price set_up_price INT DEFAULT NULL, CHANGE rental_unit_price rental_unit_price INT DEFAULT NULL, CHANGE transport_unit_price transport_unit_price INT DEFAULT NULL, CHANGE treatment_unit_price treatment_unit_price INT DEFAULT NULL, CHANGE traceability_unit_price traceability_unit_price INT DEFAULT NULL, CHANGE transport_rate transport_rate BIGINT DEFAULT NULL, CHANGE treatment_rate treatment_rate BIGINT DEFAULT NULL, CHANGE traceability_rate traceability_rate BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE quoteRequests CHANGE user_creation_id user_creation_id INT DEFAULT NULL, CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE user_in_charge_id user_in_charge_id INT DEFAULT NULL, CHANGE postal_code_id postal_code_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE deleted deleted DATETIME DEFAULT \'NULL\', CHANGE number number VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE canton canton VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE business_name business_name VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE civility civility VARCHAR(10) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE last_name last_name VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE first_name first_name VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE email email VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE phone phone VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE city city VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE total_amount total_amount INT DEFAULT NULL, CHANGE annual_budget annual_budget INT DEFAULT NULL, CHANGE frequency frequency VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE frequency_times frequency_times VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE frequency_interval frequency_interval VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE customer_id customer_id VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE reference reference VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE region CHANGE user_update_id user_update_id INT DEFAULT NULL, CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE deleted deleted DATETIME DEFAULT \'NULL\', CHANGE email email VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE users CHANGE salt salt VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE last_login last_login VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE confirmation_token confirmation_token VARCHAR(180) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE roles roles LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, CHANGE date_update date_update DATETIME DEFAULT \'NULL\', CHANGE deleted deleted DATETIME DEFAULT \'NULL\', CHANGE company_name company_name VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE last_name last_name VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE first_name first_name VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`, CHANGE lang lang VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_unicode_ci`');
    }
}
